_core:
  default_config_hash: 9O9cB-DKI5YqdkPtvZ-kiBQXXoUspp2qSZAzs0orwd0
langcode: en-gb
mode: simple
ignored_config_entities:
  - captcha.settings
  - google_tag.settings
  - recaptcha.settings
  - recaptcha_v3.settings
  - system.site
uuid: null
