_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  auto_entitylabel: -100
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  administerusersbyrole: 0
  advanced_language_selector: 0
  attachments_nugget: 0
  banners_nugget: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  cards_nugget: 0
  ckeditor5: 0
  config: 0
  config_distro: 0
  config_distro_filter: 0
  config_filter: 0
  config_ignore: 0
  config_merge: 0
  config_normalizer: 0
  config_snapshot: 0
  config_sync: 0
  config_translation: 0
  config_update: 0
  contextual: 0
  countries_info: 0
  crop: 0
  cshs: 0
  datetime: 0
  dblog: 0
  dynamic_entity_reference: 0
  easy_breadcrumb: 0
  editor: 0
  entity_reference_revisions: 0
  eu_cookie_compliance_gtm: 0
  field: 0
  field_group: 0
  field_layout: 0
  field_ui: 0
  file: 0
  filter: 0
  gin_toolbar: 0
  google_tag: 0
  help: 0
  helper_module: 0
  hide_american_english: 0
  honeypot: 0
  image: 0
  image_widget_crop: 0
  installation_profile: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  layout_paragraphs: 0
  link: 0
  linkchecker: 0
  linkit: 0
  locale: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  mysql: 0
  news_content_type: 0
  node: 0
  node_title_help_text: 0
  options: 0
  organisations_taxonomy: 0
  page_content_type: 0
  paragraphs_type_permissions: 0
  path: 0
  path_alias: 0
  permissionspolicy: 0
  person_content_type: 0
  promo_nugget: 0
  rabbit_hole: 0
  raven: 0
  recaptcha: 0
  recaptcha_v3: 0
  redirect: 0
  remora_core: 0
  remora_gdpr: 0
  remora_sections: 0
  responsive_image: 0
  seckit: 0
  security: 0
  simple_sitemap: 0
  simple_sitemap_engines: 0
  site_settings: 0
  site_settings_type_permissions: 0
  slideshow_nugget: 0
  system: 0
  tagging: 0
  tagline_nugget: 0
  taxonomy: 0
  text: 0
  text_media_nugget: 0
  token: 0
  toolbar: 0
  twig_tweak: 0
  user: 0
  views_bulk_edit: 0
  views_bulk_operations: 0
  views_ui: 0
  menu_admin_per_menu: 1
  pathauto: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  config_provider: 100
  eu_cookie_compliance: 101
theme:
  claro: 0
  gin: 0
  tonic: 0
  stable9: 0
  bootstrap5: 0
  barrio_base_theme: 0
  ds_composites: 0
profile: installation_profile
