_core:
  default_config_hash: ZhIl6m8EWHJQFZEAzV6jBaR6a-1Fwas0dZ5_PfjgobI
langcode: en-gb
scan_blocks: null
check_links_types: 1
default_url_scheme: 'http://'
base_path: ''
search_published_contents_only: false
extract:
  from_a: true
  from_audio: true
  from_embed: false
  from_iframe: true
  from_img: false
  from_object: false
  from_video: false
  filter_blacklist:
    editor_file_reference: '0'
    filter_align: '0'
    filter_url: '0'
    filter_html_escape: '0'
    filter_htmlcorrector: '0'
    filter_html_image_secure: '0'
    filter_autop: '0'
    filter_image_lazy_load: '0'
    filter_caption: '0'
    filter_html: '0'
    linkit: '0'
    media_embed: '0'
check:
  connections_max: 4
  connections_max_per_domain: 2
  disable_link_check_for_urls: |-
    example.com
    example.net
    example.org
  library: core
  interval: 2419200
  useragent: 'Drupal (+https://drupal.org/)'
error:
  action_status_code_301: 0
  action_status_code_404: 0
  ignore_response_codes: "200\r\n206\r\n302\r\n304\r\n401\r\n403"
  impersonate_account: admin
logging:
  level: 6
