root /home/ubuntu/apps/ds-composites/current/web;

client_max_body_size 256M;

location = /maintenance {
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include fastcgi_params;
    fastcgi_pass 127.0.0.1:9000;
    try_files /maintenance.php =404;
}

location = /core/install.php {
    return 301 /maintenance;
}

# Handle private files for multisites
location ~ /home/ubuntu/shared-folders/private-files/ds-composites/(ds-composites|ds-machining)/ {
    try_files $uri /index.php?$query_string;
}

# Handle public files for multisites
location ~ ^/sites/(ds-composites|ds-machining)/files/ {
    try_files $uri @rewrite;
}

# Redirect Autodiscover Requests
location ~* ^/autodiscover {
    deny all;
}

access_log /var/log/nginx/ds-composites-access.log main if=$skip_logging;
error_log /var/log/nginx/ds-composites-error.log;