label: Website-Einstellungen
display:
  default:
    display_title: Standard
    display_options:
      title: Liste
      fields:
        id:
          label: ID
          separator: ', '
        group:
          label: Gruppe
          separator: ', '
        type:
          label: Typ
          separator: ', '
        description:
          label: Beschreibung
          separator: ', '
        rendered_entity:
          label: Wert
        operations:
          label: Aktionen
      pager:
        options:
          tags:
            next: ››
            previous: ‹‹
            first: '« Erste'
            last: 'Letzte »'
          expose:
            items_per_page_label: 'Elemente pro Seite'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Versatz
      exposed_form:
        options:
          submit_button: Anwenden
          reset_button_label: Zurücksetzen
          exposed_sorts_label: 'Sortieren nach'
          sort_asc_label: Aufsteigend
          sort_desc_label: Absteigend
      filters:
        group:
          expose:
            label: Gruppe
        langcode:
          expose:
            label: Sprache
