_core:
  default_config_hash: FzFKuqOuk667AkDorrqvXkc_-M4D-Ac1XeGGusxS1JU
check_links_types: 1
default_url_scheme: 'http://'
base_path: ''
extract:
  from_a: true
  from_audio: false
  from_embed: false
  from_iframe: false
  from_img: false
  from_object: false
  from_video: false
  filter_blacklist:
    filter_align: filter_align
    filter_autop: filter_autop
    filter_caption: filter_caption
    insert_block: insert_block
    insert_view: insert_view
    smiley: smiley
    smileys: smileys
    weblinks_embed: weblinks_embed
    weblinks_filter: weblinks_filter
check:
  connections_max: 8
  connections_max_per_domain: 2
  disable_link_check_for_urls: |-
    example.com
    example.net
    example.org
  library: core
  interval: 2419200
  useragent: 'Drupal (+http://drupal.org/)'
error:
  action_status_code_301: 0
  action_status_code_404: 0
  ignore_response_codes: |-
    200
    206
    302
    304
    401
    403
  impersonate_account: placeholder-for-uid-1
logging:
  level: 6
