_core:
  default_config_hash: 2sRhnBzqTdvaE4kodkfAsed1w1NNcgfiP9UCyv7dcPc
template_key: site_settings
loader_plugin: full
disable_auto_loading: true
hide_description: true
hide_advanced: true
hide_group: true
simple_summary: true
show_groups_in_menu: true
edit_form_on_canonical_route: true
