<?php

use Drupal\remora_core\Manager\LibraryManager;

/**
 * Automatically registers all the templates in the templates/ directory
 *
 * @return array[]
 */
function tagline_nugget_theme(): array
{
  return Drupal::service('remora_core.service.module_template')->generateThemesFromTemplates('tagline_nugget');
}

function tagline_nugget_page_attachments(array &$attachments): void
{
  LibraryManager::addAdminLibrary($attachments, 'tagline_nugget/admin_styles');
}