editor:
  - 'access webform help'
  - 'access webform overview'
  - 'access webform submission user'
  - 'administer webform submission'
  - 'create webform'
  - 'edit any webform'
  - 'delete any webform'
  - 'create paragraph content webform_pod'
  - 'delete paragraph content webform_pod'
  - 'update paragraph content webform_pod'
  - 'view paragraph content webform_pod'

anonymous:
  - 'view paragraph content webform_pod'

authenticated:
  - 'view paragraph content webform_pod'
