<?php

/**
 * @file
 * Provides a taxonomy of the countries (Countries information).
 */

/**
 * Implements hook_help().
 */
function countries_info_help($path, $arg) {
  switch ($path) {
    case "help.page.countries_info":
      return '' . t("This module provides a taxonomy of the countries (Countries information) which contains information like ISO2 code, ISO3 code, name, official name, numcode.") . '';
  }
}
