<?php

/**
 *  Automatically registers all the templates in the templates/ directory
 *  @return array The theme containing the theme implementations (templates)
 */
function attachments_pod_theme(): array
{
  return Drupal::service('remora_core.service.module_template')->generateThemesFromTemplates('attachments_pod');
}

function attachments_pod_page_attachments(array &$attachments): void
{
  if (!isset($attachments['#attached']['library'])) {
    $attachments['#attached']['library'] = [];
  }
  if (Drupal::service('router.admin_context')->isAdminRoute()) {
    $attachments['#attached']['library'][] = 'attachments_pod/styles';
  }
}