<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\security\Form\HeadersConfigForm;
use Drupal\security\Cache\ConfigCache;

/**
 * Removes the configured meta tags from the <head> section.
 *
 * @code
 * <head>
 *    <meta name="Generator" content="Drupal 10 (https://www.drupal.org)">
 * </head>
 * @endcode
 * @see HeadersConfigForm
 */
function security_page_attachments_alter(array &$attachments): void
{
  $metatagsToRemove = ConfigCache::get(
    'security.settings.obfuscate_versions.metatags',
    function(): array {

      $configuredTags = Drupal::config(HeadersConfigForm::CONFIG_ID)->get('remove_metatags');
      $configuredTags = preg_split('/\r\n|\r|\n/', $configuredTags ?? '');
      return array_map('strtolower', $configuredTags);
    }
  );

  foreach($attachments['#attached']['html_head'] as $key => $attachment) {
    $name = $attachment[0]['#attributes']['name'] ?? null;
    if(!is_string($name)) {
      continue;
    }

    if(in_array(strtolower($name), $metatagsToRemove)) {
      unset($attachments['#attached']['html_head'][$key]);
    }
  }
}

function security_user_logout(): void
{
  Drupal::request()->attributes->set('_security.user_logged_out', true);
}

function security_user_login(): void
{
  Drupal::request()->attributes->set('_security.user_logged_in', true);
}

/**
 * Implements hook_form_alter().
 */
function security_form_alter(&$form, FormStateInterface $form_state, $form_id): void
{
  if ($form_id === 'seckit_settings_form') {
    $form['#attached']['library'][] = 'security/textarea_auto_height';
  }
}
