<?php

use Drupal\remora_core\Service\AddNewField;

/**
 *  Automatically registers all the templates in the templates/ directory
 * @return array The theme containing the theme implementations (templates)
 */
function news_content_type_theme(): array
{
  return Drupal::service('remora_core.service.module_template')->generateThemesFromTemplates('news_content_type');
}

/**
 * Add button classes to news link field
 *
 * Implements hook_preprocess_HOOK() for field templates.
 */
function news_content_type_preprocess_field(array &$variables): void
{
  if (($variables['element']['#field_name'] ?? null) === 'field_news_link') {
    foreach ($variables['items'] as &$item) {
      if (isset($item['content']['#url'])) {
        $item['content']['#attributes']['class'][] = 'btn btn-primary';
      }
    }
  }
}