<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\StringTranslation\ByteSizeMarkup;
use Drupal\installation_profile\Form\ConfigureThemeForm;
use Drupal\installation_profile\Manager\FigmaSassManager;
use Drupal\installation_profile\Manager\ThemeManager;
use Drupal\node\NodeInterface;

/**
 * @file
 * Barrio base theme theme file.
 */

/**
 * Adds the homepage's path to the template's variables
 *
 * @param $variables
 *
 * @return void
 */
function barrio_base_theme_preprocess(array &$variables): void
{
  $config = Drupal::config('system.site');
  $front = $config->get('page.front');
  $variables['home'] = ltrim($front, '//node//');
}

/*
 * CUSTOM FUNCTIONS
 */

/**
 * Adds size/type to file fields
 *
 * @param array $variables
 *
 * @return void
 */
function barrio_base_theme_preprocess_file_link(array &$variables): void
{
  if (isset($variables['file'])) {
    $variables['file_link_display'] = [
      'file_size' => ByteSizeMarkup::create($variables['file']->getSize()),
      'file_mime' => $variables['file']->getMimeType(),
    ];
  }
}

/**
 * Adds a form to regenerate a theme's SCSS variable files the theme settings
 * page To be used after a theme was generated using the installation_profile.
 * Form is added to the base theme, and automatically inherited by all
 * subthemes.
 *
 * @param array $form
 * @param FormStateInterface $formState
 *
 * @return void
 */
function barrio_base_theme_form_system_theme_settings_alter(array &$form, FormStateInterface $formState): void
{
  if (!class_exists(ConfigureThemeForm::class)) {
    return;
  }

  // get config form by ID
  $configForm = (new ConfigureThemeForm())->buildForm([], $formState);
  unset($configForm['actions']);

  $configForm['theme_name']['#type'] = 'hidden';
  $configForm['theme_name']['#default_value'] = $formState->getBuildInfo()['args'][0];

  // add the figma files field
  $form['generation'] = [
    '#type' => 'details',
    '#title' => t('Generation'),
    '#description' => t('Regenerate a (sub) theme\'s variable files. Supply all the files you want to regenerate. <b>WARNING:</b> This will overwrite any existing files.'),
    '#open' => TRUE,
    'figma_files' => $configForm,
  ];

  // add submit handler
  $form['actions']['submit']['#submit'][] = 'barrio_base_theme_form_system_theme_settings_alter_submit';
}

/**
 * Handles the submission of theme settings
 *
 * @param array $form
 * @param FormStateInterface $formState
 *
 * @return void
 */
function barrio_base_theme_form_system_theme_settings_alter_submit(array &$form, FormStateInterface $formState): void
{
  $figmaFiles = $formState->getValue('figma_files');
  $themeName = $formState->getValue('theme_name');

  // if we have at least 1 figma file
  if ($formState->hasValue('figma_files') && !empty($figmaFiles)) {
    try {
      // human-readable name is irrelevant
      $scssFiles = FigmaSassManager::fromUploadedFile($figmaFiles)->toScss();
      $themeManager = new ThemeManager($themeName, '');

      // now add files that are uploaded
      $manager = $themeManager->addScssFiles($scssFiles);

      // do not init! This would throw an exception since the theme already exists
      $manager->write();
      Drupal::messenger()->addMessage("Successfully regenerated SCSS files for theme: $themeName.");
    } catch(Exception $e) {
      Drupal::messenger()->addError($e->getMessage());
    }
  }
}

/**
 * Change login form labels and placeholders.
 */
function barrio_base_theme_form_user_login_form_alter(&$form, Drupal\Core\Form\FormStateInterface $form_state, $form_id): void
{
  //- change label/placeholder for username input
  $form['name']['#title'] = t('Email address / username');
  $form['name']['#attributes']['placeholder'] = t('Enter your email address or username');
  $form['name']['#description'] = t('');

  //- change label/placeholder for password input
  $form['pass']['#attributes']['placeholder'] = t('Enter your password');
}

/**
 * Add has-hero class to body if present
 */
function barrio_base_theme_preprocess_html(array &$variables): void
{
  $route_match = \Drupal::routeMatch();
  $node = $route_match->getParameter('node');
  if ($node instanceof NodeInterface) {
    if ($node->hasField('field_landing') && !empty($node->get('field_landing')->value)) {
      $variables['attributes']['class'][] = 'landing-page';
    }

    if ($node->hasField('field_hero_content') && !$node->get('field_hero_content')
        ->isEmpty()) {
      foreach ($node->get('field_hero_content')
                 ->referencedEntities() as $paragraph) {
        if ($paragraph->bundle() === 'section') {
          $variables['attributes']['class'][] = 'has-hero';
        }
      }
    }
  }
}
