label: 'Nedavni komentarji'
display:
  default:
    display_title: Privzeto
    display_options:
      title: 'Nedavni komentarji'
      empty:
        area_text_custom:
          content: 'Ni komentarjev.'
  block_1:
    display_title: Blok
    display_options:
      block_description: 'Nedavni komentarji'
