display:
  default:
    display_title: Privzeto
    display_options:
      fields:
        filename:
          label: Ime
        filemime:
          label: 'MIME type'
        filesize:
          label: Velikost
        status:
          label: Stanje
        count:
          label: 'Uporabljen v'
        operations:
          label: Operacije
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Ponastavi
      filters:
        filename:
          expose:
            label: 'Ime datoteke'
        filemime:
          expose:
            label: 'MIME type'
        status:
          expose:
            label: Stanje
  page_2:
    display_options:
      arguments:
        fid:
          exception:
            title: Vsi
