<?php

use Drupal\remora_core\Manager\LibraryManager;

/**
 *  Automatically registers all the templates in the templates/ directory
 *  @return array The theme containing the theme implementations (templates)
 */
function promo_nugget_theme(): array
{
  return Drupal::service('remora_core.service.module_template')->generateThemesFromTemplates('promo_nugget');
}

function promo_nugget_page_attachments(array &$attachments): void
{
  LibraryManager::addAdminLibrary($attachments, 'promo_nugget/admin_styles');
}