display:
  default:
    display_title: Privzeto
    display_options:
      title: 'Kdo je prijavljen'
      exposed_form:
        options:
          reset_button_label: Ponastavi
      filters:
        access:
          expose:
            label: 'Zadnji dostop'
            description: 'Uporabnik se smatra prijavljen še toliko časa po zadnjem ogledu strani.'
  who_s_online_block:
    display_title: 'Kdo je prijavljen'
    display_options:
      block_description: 'Kdo je prijavljen'
