<?php

use Drupal\node\Entity\Node;
use Drupal\remora_core\Service\AddNewField;

/**
 *  Automatically registers all the templates in the templates/ directory
 * @return array The theme containing the theme implementations (templates)
 */
function page_content_type_theme(): array
{
  return Drupal::service('remora_core.service.module_template')->generateThemesFromTemplates('page_content_type');
}
