editor:
  - 'access taxonomy overview'
  - 'create terms in cit_countries_information'
  - 'create terms in regions'
  - 'delete terms in cit_countries_information'
  - 'delete terms in regions'
  - 'edit terms in cit_countries_information'
  - 'edit terms in regions'
